config/routes.rb
Rails.application.routes.draw do
  get "login", to: 'sessions#new'
  post "login", to: 'sessions#create'
  delete "logout", to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
  get "signup", to: "users#new"
  resources :users, only: [:new, :create]
  resources :tasks 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence:true, length:{maximum:255}
  validates :status, presence:true, length:{maximum:10}
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email.downcase!}
    has_secure_password
    validates :name, presence:true, length:{ maximum:50 }
    validates :email, presence:true, length: {maximum:255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
    private 
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email= params[:session][:email].downcase
    password= params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end 
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private 
    def login(email, password)
      @user = User.find_by(email: email)
      if @user && @user.authenticate(password)
        #ログイン成功
        session[:user_id] = @user.id
        return true
      else 
        #ログイン失敗
        return false
      end 
    end
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only:[:show, :edit, :update, :destroy]

  def index
    @task = current_user.tasks.all
  end 
 
  def create 
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = "Taskが追加されました"
      redirect_to tasks_url
    else 
      flash.now[:danger] = "Taskは追加されませんでした"
      render :new
    end 
    
  end
  
  def new
    @task = Task.new
  end
  
  def update
    if @task.update(task_params)
      flash[:success] = "Taskが編集されました"
      redirect_to @task 
    else 
      flash.now[:danger] = "Taskは編集されませんでした"
      render :edit
    end 
  end 
  
  def destroy
    @task.destroy
    
    flash[:success] = "Taskは削除されました"
    redirect_to tasks_url
  end 

  private 
  #Strong Parameter

  def task_params 
    params.require(:task).permit(:content, :status)
  end 
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end 
  end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "登録に成功しました"
      redirect_to login_url
    else
      flash[:danger] = "登録に失敗しました"
      render :new
    end 
  end 
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user 
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if user.errors.any? %>
  <div class="alert">
    <ul>
      <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/flash_messages" %>
      
      <%= yield%>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |f| %>
  
  <%= f.label :status, "状況" %>
  <%= f.text_field :status %>
  <%= f.label :content, "タスク" %>
  <%= f.text_field :content %>
  
  <%= f.submit "追加" %>
<% end %>

app/views/tasks/edit.html.erb
<p><%= @task.id %>の編集ページ</p>

<%= render "form", task: @task %>

<%= link_to "戻る", tasks_path %>

app/views/tasks/index.html.erb
<p>ログイン完了ユーザ：<%= current_user.name %></p>
<%= link_to "Logout", logout_path, method: :delete %>
<h1>タスク一覧</h1>
<ul>
  <% @task .each do |task| %>
  <li><%= link_to task.id, task %> : <%= task.status %> &gt; <%= task.content %></li>
  <% end %>
</ul>
<%= link_to "新規タスク作成", new_task_path %>

app/views/tasks/new.html.erb
<h1>新規タスク作成</h1>

<%= render "form", task: @task %>

<%= link_to "戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.id %>の詳細ページ</h1>
<p>状況:<%= @task.status %></p>
<p>タスク:<%= @task.content %></p>
<%= link_to "一覧に戻る", tasks_path %>
<%= link_to "このタスクを編集する" ,edit_task_path(@task) %>
<%= link_to "このタスクを削除する", @task, method: :delete, data: {confirm: "本当に削除してよろしいですか？"} %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<div>
    <%= form_with(model: @user) do |f| %>
    <%= render "layouts/error_messages", user: f.object %>
    <div>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :email, "Email" %>
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <div>
      <%= f.label :password, "Password" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    
    <%= f.submit "Sign up", class: "btn btn-primary" %>
    <% end %>
    <%= link_to "Login", login_path %>
</div>